import Head from "next/head";
import Form from "../components/form";
import * as S from './styles'

export default function Home() {
  return (
    <>
      <Head>
        <title>Lennas MP3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.GlobalStyle />
      <S.Wrapper>
        <S.Container>
          <S.Logo>
            <S.LogoName>
            LennaYT
            </S.LogoName>
          </S.Logo>
          <Form />
          {/* <S.GithubLink><a href=''>Frontend</a><a href=''>Backend</a></S.GithubLink> */}
        </S.Container>
      </S.Wrapper>
    </>
  );
}
