import Head from 'next/head'
import Form from '../src/components/form'



export default function Home() {


  return (
    <>
      <Head>
        <title>Lennas MP3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Form />
    </>
  )
}
